server:
  port: 8003    #default port where the service will be started

spring:    
  application:
    name: kubernete-backend  
  profiles:
    active: development
      
     
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
    
logging:
  level:
    com.example.controller: DEBUG


  