server:
  port: 8098    #default port where the service will be started
 
#eureka:         #tells about the Eureka server details and its refresh time
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#  client:
#    serviceUrl:
#      defaultZone: http://eureka:8761/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5
# 
spring:    
  application:
    name: config-server-client   #current service name to be used by the eureka server
  cloud:
    config:
      uri: http://localhost:8888
  profiles:
    active: development
      
     
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
    
logging:
  level:
    com.example.controller: DEBUG


  