#HTTP server port ( microservice port)
server:
  port: 8888
  
 #Spring Cloud Config Server Repository
spring:
  cloud:
   config:
    server:
      git:
        uri: file://${user.home}/git_repo/spring_cloud_services
    
#Disable security of the Management endpoint
management:
  security:
    enabled: false   